### ISSUE TITLE
 Failing to build Wallride-ui-admin package

### ISSUE THREAD

**Issue by kyeljmd** [tagbangers/wallride#104]
Failing to build Wallride-ui-admin package

I have executed the ff: command for the initial setup and installation.
`mvn spring-boot:run -Pjar -Drun.jvmArguments="-Dwallride.home=file:wallride-home"`

And this returned an error

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\kyel\\Projects\\wallride\\.node\\node\\node.exe',
1 verbose cli   'C:\\Users\\kyel\\Projects\\wallride\\.node\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle wallride-ui-admin@1.0.0~prebuild: wallride-ui-admin@1.0.0
6 silly lifecycle wallride-ui-admin@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle wallride-ui-admin@1.0.0~build: wallride-ui-admin@1.0.0
8 verbose lifecycle wallride-ui-admin@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle wallride-ui-admin@1.0.0~build: PATH: C:\Users\kyel\Projects\wallride\.node\node\node_modules\npm\bin\node-gyp-bin;C:\Users\kyel\Projects\wallride\wallride-ui-admin\node_modules\.bin;C:\Users\kyel\Projects\wallride\wallride-core\..\.node\node;C:\cmder\bin;C:\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\cmder\vendor\conemu-maximus5;C:\cmder\vendor\conemu-maximus5\ConEmu;E:\Python36\Scripts\;E:\Python36\;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;E:\Scala\bin;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;E:\nodejs\;E:\Yarn\bin;E:\Go\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\maven\bin;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Users\kyel\AppData\Local\Microsoft\WindowsApps;E:\MongoDB\Server\3.4\bin;C:\Users\kyel\AppData\Roaming\npm;C:\Users\kyel\AppData\Local\Yarn\bin;E:\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;C:\cmder\;
10 verbose lifecycle wallride-ui-admin@1.0.0~build: CWD: C:\Users\kyel\Projects\wallride\wallride-ui-admin
11 silly lifecycle wallride-ui-admin@1.0.0~build: Args: [ '/d /s /c', 'webpack -p' ]
12 silly lifecycle wallride-ui-admin@1.0.0~build: Returned: code: 2  signal: null
13 info lifecycle wallride-ui-admin@1.0.0~build: Failed to exec build script
14 verbose stack Error: wallride-ui-admin@1.0.0 build: `webpack -p`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\kyel\Projects\wallride\.node\node\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\kyel\Projects\wallride\.node\node\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid wallride-ui-admin@1.0.0
16 verbose cwd C:\Users\kyel\Projects\wallride\wallride-ui-admin
17 error Windows_NT 10.0.16299
18 error argv "C:\\Users\\kyel\\Projects\\wallride\\.node\\node\\node.exe" "C:\\Users\\kyel\\Projects\\wallride\\.node\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error wallride-ui-admin@1.0.0 build: `webpack -p`
22 error Exit status 2
23 error Failed at the wallride-ui-admin@1.0.0 build script 'webpack -p'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wallride-ui-admin package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack -p
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs wallride-ui-admin
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls wallride-ui-admin
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by marcosjunqueira** [comment]
It worked for me, but I had to change the webpack.config.js as below.

`rules: [
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: "css-loader"
                })
            },
            {
                test: /\.(jpg|png|gif)$/,
                use: 'url-loader',
            },
            {
                test: /\.(ttf|otf|eot|svg|woff2?)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                exclude: /node_modules/,
                loader: 'file-loader',
                options: {
                    name: '[path][name].[ext]',
//                    publicPath: './font/',
                    emitFile: false
                }
            },
            {
                test: /\.(ttf|otf|eot|svg|woff2?)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                include: /node_modules/,
                loader: 'file-loader',
                options: {
                    name: '[path][name].[ext]',
                    emitFile: false
                }
            }
        ]`
